### ISSUE TITLE
[Feat] 물풍선 폭발 범위에 물줄기(이펙트) 생성

### ISSUE THREAD

**Issue by nninyeong** [KIA-PROGRAMMING-38/CrazyArcade#8]
# 설명
1. 물풍선의 범위에 해당하는 위치에 물줄기(이펙트)를 생성하고 애니메이션을 재생합니다.
- 물줄기는 한 번에 전체 길이만큼 생성되지 않고, 마지막 범위에 가까운 영역일수록 천천히 생성되어 한 칸씩 나아가듯 보여집니다.
- 물풍선이 놓인 위치에 가까운 두 칸은 한 번에 한 칸 나아가며, 그 이후는 두 칸 나아가 점점 빠르게 퍼져나가듯 보이게 합니다.
2. 가장 마지막 범위에는 중간 범위의 물줄기와 다른 스프라이트를 가진 물줄기가 생성되어야 합니다.
3. 물풍선이 설치되어있던 위치에도 애니메이션이 재생됩니다.

# 참고자료
![image](https://user-images.githubusercontent.com/74064375/230293005-2046b18c-cea7-43e3-8b9b-adc6a4ce777b.png)
-폭발 직후

![image](https://user-images.githubusercontent.com/74064375/230293244-b4bebb33-c61b-4f8f-876a-d46d13e8a573.png)
- 폭발 후 약간의 시간 경과

**Comment by ChoiSeonMun** [comment]
#7 과 통합
